# Generated by Django 3.1.3 on 2020-12-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
